ReactDOM.render(
  <div>
    <ul>
      <li>One</li>
      <li>Two</li>
      <li>Three</li>
      <li>Four</li>
      <li>Five</li>
    </ul>
    <h1>HI</h1>
    <h1>HI</h1>
  </div>,
  document.getElementById("root")
);
